Lok 70 pipeline
Liatrio-LOK/spring-petclinic pull request #2
Opened 2017-11-14 22:00 UTC by JGuzman4

Adding a Jenkinsfile for building and deploying petclinic in openshift. A few of the Openshift plugins for jenkins give us pipeline DSL to use, so this is what this pipeline is using

2017-11-14 22:10 UTC, ebracho requested changes
Looks good! It looks like the OpenShift plugin integrates pretty seamlessly with Jenkinsfile pipelines. I have a few questions though:

1. Does this run against OpenShift objects in a specific project? Also, is there a way to specify a project when referring to objects in these pipeline steps.

2. Can you include the config files for provisioning these objects in the repo? From what I can see, there's a buildConfig imageStream, deployConfig, and service all named `spring-petclinic`.

3. I'm curious about the 'Scale Deployment' stage at the beginning of the pipeline is for, could you elaborate on that?

2017-11-14 22:22 UTC, JGuzman4 commented
Thanks Eddie. So the pipeline assumes there is a buildConfig, imagestream, deployConfig, and serviceConfig already setup inside the same namespace as the jenkins instance. And yes, you can specify the project when referring to the objects.

The Scale Deployment stage is only there for PoC. I tried to follow along the layout of the sample project that Openshift's jenkins, so thats the only reason that is in there. I'm agnostic as to whether we should keep it or not

2017-11-14 22:30 UTC, ebracho approved these changes

2017-11-14 22:32 UTC, ebracho commented
Cool, thanks for the clarifications. I still have a lot to learn about application lifecycle in OpenShift - looking forward to the demo!

2017-11-15 18:08 UTC, jbankes approved these changes
LGTM

2017-11-15 23:26 UTC, merged